version: "3.8"

networks:
  app:
    driver: bridge

volumes: 
  dbdata:

services: 

  nginx:
    image: nginx:1.21.3-alpine
    container_name: webserver
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./infrastructure/webserver/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - postgres
    networks:
      - app

  php:
    build:
      context: ./infrastructure/php
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "9000:9000"
    volumes:
      - ./src:/var/www/html
    networks:
      - app

  postgres:
    image: postgres:14.0-alpine
    container_name: database
    restart: unless-stopped
    tty: true
    ports:
      - "5432:5432"
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_SCHEMA}
      SERVICE_TAGS: ${APP_ENV}
      SERVICE_NAME: postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./infrastructure/init:/docker-entrypoint-initdb.d/
    networks:
      - app
